CarsAdvisors/Controllers/MakerController.cs
using CarsAdvisors.Models;
using CarsAdvisors.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;

namespace CarsAdvisors.Controllers
{
    [Authorize(Roles = "Admin")]

    public class MakerController : Controller
    {
         Cars Context=new Cars();

        public IHostingEnvironment Hosting { get; }

        public MakerController(IHostingEnvironment hosting)
        {
            Hosting = hosting;

        }
        public IActionResult Delete(int id)
        {

            Maker oldMaker = Context.Makers.FirstOrDefault(d => d.ID == id);
            Context.Makers.Remove(oldMaker);
            Context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["count"] = Context.Compares.Where(c => c.User_ID == userID).Count();

            var Maker = Context.Makers.FirstOrDefault(d => d.ID == id);

            return View(Maker);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(int id, Maker newmaker, IFormFile File)
        {
            if (File != null)
            {
                string uploads = Path.Combine(Hosting.WebRootPath, "Images");
                string filename = File.FileName;
                string fullpath = Path.Combine(uploads, filename);
                File.CopyTo(new FileStream(fullpath, FileMode.Create));
                newmaker.MakerImage = filename;
            }

            if (ModelState.IsValid == true)
            {
                Maker oldMaker = Context.Makers.FirstOrDefault(d => d.ID == id);
                oldMaker.MakerName = newmaker.MakerName;
                oldMaker.MakerImage = newmaker.MakerImage;
                Context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View("Edit", newmaker);
        }
        public IActionResult Index()
        {
            var userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["count"] = Context.Compares.Where(c => c.User_ID == userID).Count();
            ViewData["Make"] = Context.Makers.ToList();
            List<Maker> makers = Context.Makers.ToList();
            return View(makers);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(IFormFile File, Maker Newobj)
        {
            if (File != null)
            {
                string uploads = Path.Combine(Hosting.WebRootPath, "Images");
                string filename = File.FileName;
                string fullpath = Path.Combine(uploads, filename);
                File.CopyTo(new FileStream(fullpath, FileMode.Create));
                Newobj.MakerImage = filename;
            }

            if (ModelState.IsValid == true)
            {
                Context.Makers.Add(Newobj);
                 Context.SaveChanges();
                return RedirectToAction("index");
            }
            return View("New", Newobj);
        }
        public IActionResult New()
        {
            var userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["count"] = Context.Compares.Where(c => c.User_ID == userID).Count();
            return View();
        }
    }
}

CarsAdvisors/Controllers/ReviewsController.cs
using CarsAdvisors.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;

namespace CarsAdvisors.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ReviewsController : Controller
    {
        Cars Context=new Cars();
        public IActionResult Index()
        {
            var userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["count"] = Context.Compares.Where(c => c.User_ID == userID).Count();
            var Reviews = Context.News_Reviews.ToList();
            return View(Reviews);
        }
        public IActionResult New()
        {
            var userID = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["count"] = Context.Compares.Where(c => c.User_ID == userID).Count();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(News_Reviews Newobj)
        {
            
            if (ModelState.IsValid == true)
            {
                Context.News_Reviews.Add(Newobj);
                Context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View("New", Newobj);
        }
        public IActionResult Delete(int id)
        {

            News_Reviews old = Context.News_Reviews.FirstOrDefault(d => d.ID == id);
            Context.News_Reviews.Remove(old);
            Context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CarsAdvisors/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cars Advisors</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Beau+Rivage&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/style.css">
</head>

<body>
    <div class="contact">
        <div class="container">
            <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-around ">
                <span class="my-2">
                        <img src="/Images/239502970_106315815098939_167385082857820009_n.png" class="rounded-circle me-2" width="50px" height="50px" alt="">
                        <span class="text-white">Hossam Zaki</span>
                </span>
                <span class="my-2 ">
                        <i class="bi bi-telephone fs-4 text-danger"></i>
                        <span class="text-white">
                        +20 101 190 9018

                        </span>
                </span>
                <span class="icons my-3 ">
                    <a href="https://www.facebook.com/CarsAdvisors" target="_blank" class="mx-1">
                        <i class="bi bi-facebook fs-4 text-info"></i>

                    </a>
                    <a href="https://www.youtube.com/channel/UCEhf-AIjZkzQtBs8Hq7m8kA" target="_blank" class="mx-1">
                        <i class="bi bi-youtube fs-4 text-danger"></i>

                    </a>
                    <a href="https://www.instagram.com/cars_advisors_by_hossam_zaki/" target="_blank" class="mx-1">
                        <i class="bi bi-instagram fs-4 text-warning"></i>

                    </a>
                </span>
            </div>
        </div>
    </div>
    <!-- Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
                @*<img src="/Images/logo w BG.png" alt="" width="200" height="200">*@
        </a>
            
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0  ">
                    <li class="nav-item me-2">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item me-4">
                        <a class="nav-link" asp-controller="Model" asp-action="Index">Cars</a>
                    </li>
                    <li class="nav-item me-4">
                        <a class="nav-link" asp-controller="Compare" asp-action="Compare">
                            Compare 
                            <i class="bi bi-compass text-white"> </i>
                            <span class="badge badge-warning lblCartCount">@ViewBag.count </span>

                        </a>

                    </li>
                    @if(User.IsInRole("Admin"))
                        {
                    <li class="nav-item me-4">
                        <div class="dropdown">
                              <button class="btn text-white dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Features
                              </button>
                              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="AddAdmin">Add New Admin</a></li>
                                <li><a class="dropdown-item"  asp-controller="Maker" asp-action="New">All Make</a></li>
                                <li><a class="dropdown-item"  asp-controller="Reviews" asp-action="Index">All Reviews</a></li>
                              </ul>
                        </div>
                    </li>
                    }
                    <li class="nav-item me-4">
                        <form asp-controller="Model" asp-action="Search" class="d-flex">
                            <input name="Model" class="form-control me-1 " style="width:250px!important" type="search" placeholder="Search By Make or Model" aria-label="Search">
                            <button class="search btn btn-outline-white bg-white text-black" type="submit">Search</button>
                        </form>

                    </li>
                    <li class="nav-item login text-lg-end ms-lg-3 d-flex ">
                        <i class="bi bi-person-circle text-white mx-3 fs-4 "></i>
                @if (User.Identity.IsAuthenticated == true)
                        {
                            <span class="my-auto">
                                 <a class="text-white" > @User.Identity.Name</a>
                            </span>
                            <span class="ms-4">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </span>
                        }else{
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        }

                    </li>
                    <li class="nav-item ms-4">
                    </li>
                </ul>

            </div>

</nav>
<div id="search"></div>
<!-- Slider -->
    <div id="carouselExampleCaptions" class="carousel slide masthead" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/Images/ab36a96476705e7724ee5c4935b6fed7.gif" class="d-block w-100" alt="..." height="5%">
                <div class="carousel-caption d-none d-md-block" data-aos="fade-up" data-aos-easing="linear" data-aos-duration="1500">
                </div>
            </div>
        </div>
    </div>
    <!-- Content-->
    <div class="container">
        <div class="row text-center my-4">
            <div class="col-lg-12 col-md-12 col-lg-12">
                <h3 class="fs-1">RECENT <span style="color: orange;"> CARS</span></h3>
            </div>
            <div >
                @RenderBody();
            </div>
        </div>

        <div class="row text-center ">
            <div class="col-sm-12 col-md-12 col-lg-12">
                      <h3  class="fs-1 mb-5">RECENT <span style="color: orange;"> REVIEWS</span></h3>
            </div>
        </div>
               <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000"  id="carouselExampleControlsNoTouching" class="carousel slide" data-bs-touch="false" data-bs-interval="false">
          <div class="carousel-inner">
            <div class="carousel-item active">
                    <iframe width="100%" height="500" src="https://www.youtube.com/embed/5PGno1EAFRs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            @foreach (var item in ViewBag.Review)
           {
               
            <div class="carousel-item">
                  <iframe width="100%" height="500" src="@item.VideoURL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

            </div>
           }
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        </div>
    <!-- Footer-->
    <footer>
        <div class="row text-center ">
            <div class="col-sm-12 col-md-6 col-lg-6 text-center mx-auto my-5">
                <h4><span style="color: white;">Cars</span> <span style="color: orange;">Advisors</span></h4>
                <p class="text-white">We will talk about everything related to cars and compare them</p>

            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 mx-auto my-5">
                <h4 class="text-white">Follow us</h4>
                 <div class="icons my-3 ">
                    <a href="https://www.facebook.com/CarsAdvisors" target="_blank" class="mx-1">
                        <i class="bi bi-facebook fs-4 text-info"></i>

                    </a>
                    <a href="https://www.youtube.com/channel/UCEhf-AIjZkzQtBs8Hq7m8kA" target="_blank" class="mx-1">
                        <i class="bi bi-youtube fs-4 text-danger"></i>

                    </a>
                    <a href="https://www.instagram.com/cars_advisors_by_hossam_zaki/" target="_blank" class="mx-1">
                        <i class="bi bi-instagram fs-4 text-warning"></i>

                    </a>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <p class="text-white">© 2022 Cars Advisors</p>
            </div>

        </div>

    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js " integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4 " crossorigin="anonymous "></script>
 <script src="/lib/jquery/dist/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    <script src="/js/script.js"></script>

</body>

</html>

CarsAdvisors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cars Advisors</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Beau+Rivage&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"/>
</head>

<body>
    <div class="contact">
        <div class="container">
            <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-around ">
                <span class="my-2">
                        <img src="/Images/239502970_106315815098939_167385082857820009_n.png" class="rounded-circle me-2" width="50px" height="50px" alt="">
                        <span class="text-white">Hossam Zaki</span>
                </span>
                <span class="my-2 ">
                        <i class="bi bi-telephone fs-4 text-danger"></i>
                        <span class="text-white">
                        +20 101 190 9018

                        </span>
                </span>
                <span class="icons my-3 ">
                    <a href="https://www.facebook.com/CarsAdvisors" target="_blank" class="mx-1">
                        <i class="bi bi-facebook fs-4 text-info"></i>

                    </a>
                    <a href="https://www.youtube.com/channel/UCEhf-AIjZkzQtBs8Hq7m8kA" target="_blank" class="mx-1">
                        <i class="bi bi-youtube fs-4 text-danger"></i>

                    </a>
                    <a href="https://www.instagram.com/cars_advisors_by_hossam_zaki/" target="_blank" class="mx-1">
                        <i class="bi bi-instagram fs-4 text-warning"></i>

                    </a>
                </span>
            </div>
        </div>
    </div>
    <!-- Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
                @*<img src="/Images/logo w BG.png" alt="" width="200" height="200">*@
        </a>
            
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0  ">
                    <li class="nav-item me-2">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item me-4">
                        <a class="nav-link" asp-controller="Model" asp-action="Index">Cars</a>
                    </li>
                    <li class="nav-item me-4">
                        <a class="nav-link" asp-controller="Compare" asp-action="Compare">
                            Compare 
                            <i class="bi bi-compass text-white"> </i>
                            <span  class="badge badge-warning lblCartCount">@RenderSection("Count",true) </span>

                        </a>

                    </li>
                    @if(User.IsInRole("Admin"))
                        {
                    <li class="nav-item me-4">
                        <div class="dropdown">
                              <button class="btn text-white dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Features
                              </button>
                              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="AddAdmin">Add New Admin</a></li>
                                <li><a class="dropdown-item"  asp-controller="Maker" asp-action="New">All Make</a></li>
                                <li><a class="dropdown-item"  asp-controller="Reviews" asp-action="Index">All Reviews</a></li>
                              </ul>
                        </div>
                    </li>
                    }
                    <li class="nav-item me-4">
                        <form asp-controller="Model" asp-action="Search" class="d-flex">
                            <input name="Model" class="form-control me-1 " style="width:250px!important" type="search" placeholder="Search By Make or Model" aria-label="Search">
                            <button class="search btn btn-outline-white bg-white text-black" type="submit">Search</button>
                        </form>

                    </li>
                   <li class="nav-item login text-lg-end ms-lg-3 d-flex ">
                        <i class="bi bi-person-circle text-white mx-3 fs-4 "></i>
                @if (User.Identity.IsAuthenticated == true)
                        {
                            <span class="my-auto">
                                 <a class="text-white" > @User.Identity.Name</a>
                            </span>
                            <span class="ms-4">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </span>
                        }else{
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        }

                    </li>
                </ul>

            </div>

</nav>
<div>
    @RenderBody();
</div>
    <!-- Footer-->
    <footer>
        <div class="row text-center ">
            <div class="col-sm-12 col-md-6 col-lg-6 text-center mx-auto my-5">
                <h4><span style="color: white;">Cars</span> <span style="color: orange;">Advisors</span></h4>
                <p class="text-white">We will talk about everything related to cars and compare them</p>

            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 mx-auto my-5">
                <h4 class="text-white">Follow us</h4>
                 <div class="icons my-3 ">
                    <a href="https://www.facebook.com/CarsAdvisors" target="_blank" class="mx-1">
                        <i class="bi bi-facebook fs-4 text-info"></i>

                    </a>
                    <a href="https://www.youtube.com/channel/UCEhf-AIjZkzQtBs8Hq7m8kA" target="_blank" class="mx-1">
                        <i class="bi bi-youtube fs-4 text-danger"></i>

                    </a>
                    <a href="https://www.instagram.com/cars_advisors_by_hossam_zaki/" target="_blank" class="mx-1">
                        <i class="bi bi-instagram fs-4 text-warning"></i>

                    </a>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <p class="text-white">© 2022 Cars Advisors</p>
            </div>

        </div>

    </footer>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js " integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4 " crossorigin="anonymous "></script>
    <script src="/lib/jquery/dist/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <script>
        AOS.init();
    </script>
    <script src="/js/script.js"></script>
    <script>
        function Collapse(){
            var element=document.getElementById("navbarSupportedContent");
            element.style.display="visible";
        }
    </script>
</body>

</html>

CarsAdvisors/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cars Advisors</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Beau+Rivage&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"/>
</head>

<body>
<div>
    @RenderBody();
</div>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js " integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4 " crossorigin="anonymous "></script>
    <script src="/lib/jquery/dist/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <script>
        AOS.init();
    </script>
    <script src="/js/script.js"></script>
    <script>
        function Collapse(){
            var element=document.getElementById("navbarSupportedContent");
            element.style.display="visible";
        }
    </script>
</body>

</html>